// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwo9cGthcbHtA1UV1kQ_-9s0zuIlyBml4',
    appId: '1:512984318818:web:9721e3244a0e4e7043223b',
    messagingSenderId: '512984318818',
    projectId: 'test-firebase-3d494',
    authDomain: 'test-firebase-3d494.firebaseapp.com',
    databaseURL: 'https://test-firebase-3d494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-3d494.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3bV2NKE1Hz068zt2Z5ddHv6xjUqnkFU8',
    appId: '1:512984318818:android:4b12aa382bd7b01643223b',
    messagingSenderId: '512984318818',
    projectId: 'test-firebase-3d494',
    databaseURL: 'https://test-firebase-3d494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-3d494.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnrZzr3z_YAmEYDS-bWcyq9oOVZfJT9Rs',
    appId: '1:512984318818:ios:49d73d3c8104089443223b',
    messagingSenderId: '512984318818',
    projectId: 'test-firebase-3d494',
    databaseURL: 'https://test-firebase-3d494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-3d494.appspot.com',
    iosClientId: '512984318818-ukdps4mbl83lrskh516j9rqncen89977.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotGpt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnrZzr3z_YAmEYDS-bWcyq9oOVZfJT9Rs',
    appId: '1:512984318818:ios:2c872cf50805e5b643223b',
    messagingSenderId: '512984318818',
    projectId: 'test-firebase-3d494',
    databaseURL: 'https://test-firebase-3d494-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'test-firebase-3d494.appspot.com',
    iosClientId: '512984318818-vffi8dc4adb69tlm5pg62d1rp299tr8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatbotGpt.RunnerTests',
  );
}
